apiVersion: v1 
kind: Service 
metadata: 
  name: hoobank 
  namespace: hoobank
  labels: 
    app: hoobank
spec:
  type: LoadBalancer 
  ports:
    - port: 80 
      targetPort: 8080
  selector:
    app: hoobank